package issue.sandbox;

/*Generated by MPS */

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.io.IOException;

public class map_Main {
  public static void main(String[] args) {
    BufferedReader reader = new BufferedReader(new InputStreamReader(System.in));
    int i = 0;
    try {
      i = Integer.valueOf(reader.readLine());
    } catch (IOException e) {
    }
    System.out.println(i * i);
  }
}
